#讀blue noise
customTexture.blue_noise_tex = textures/blue_noise.png
iris.features.required = CUSTOM_IMAGES COMPUTE_SHADERS
image.voxelGrid = voxelSampler rgba rgba8 float false true 1.0 1.0 1.0 1.0




#遊戲設定開關
screen = \
    [denoise] \
    [sspt] \
    [ssao] \
    Ambient_Strength

screen.sspt = \
    Ray_Max_Step \
    Ray_Step_Size \
    Avoid_Fuck_Bright_Value \
    Indirect_Light_Strengh \
    Min_Penetration_Depth \
    Thickness \
    Ray_Start_Bias \
    Indirect_Light_Reflection_Rate \
    Sspt

screen.denoise = \
    Bilateral_Denoise

sliders = \
    Ray_Max_Step \
    Ray_Step_Size \
    Avoid_Fuck_Bright_Value \
    Indirect_Light_Strengh \
    Ambient_Strength \
    Min_Penetration_Depth \
    Thickness \
    Ray_Start_Bias \
    Indirect_Light_Reflection_Rate
