#讀blue noise
customTexture.blue_noise_tex = textures/blue_noise.png


#不開別想 存/讀 voxel
iris.features.required = CUSTOM_IMAGES
#體素的其中一個存放位置在shadow.fsh/vsh，不開沒法讀
shadow.enabled=true
#把gl_Color的狗屎ao從.rgb移動到.a
separateAo=true
#確保體素在身後不要被切掉
shadow.culling=reversed




#遊戲設定開關
screen = \
    [denoise] \
    [sspt] \
    [ssao] \
    Ambient_Strength

screen.sspt = \
    Ray_Max_Step \
    Ray_Step_Size \
    Avoid_Fuck_Bright_Value \
    Indirect_Light_Strengh \
    Min_Penetration_Depth \
    Thickness \
    Ray_Start_Bias \
    Indirect_Light_Reflection_Rate \
    Sspt

screen.denoise = \
    Bilateral_Denoise

sliders = \
    Ray_Max_Step \
    Ray_Step_Size \
    Avoid_Fuck_Bright_Value \
    Indirect_Light_Strengh \
    Ambient_Strength \
    Min_Penetration_Depth \
    Thickness \
    Ray_Start_Bias \
    Indirect_Light_Reflection_Rate
