#讀blue noise
customTexture.blue_noise_tex = textures/blue_noise.png




#遊戲設定開關
screen = \
    [denoise] \
    [sspt] \
    [ssao] \
    Ambient_Strength

screen.sspt = \
    Ray_Max_Step \
    Ray_Step_Size \
    Avoid_Fuck_Bright_Value \
    Indirect_Light_Strengh \
    Depth_Hit_Bias \
    Thickness \
    Ray_Start_Bias

screen.denoise = \
    Bilateral_Denoise

sliders = \
    Ray_Max_Step \
    Ray_Step_Size \
    Avoid_Fuck_Bright_Value \
    Indirect_Light_Strengh \
    Ambient_Strength \
    Depth_Hit_Bias \
    Thickness \
    Ray_Start_Bias
